### ISSUE TITLE
ml-1m数据集的具体介绍与处理的传送门消失了

### ISSUE THREAD

**Issue by timor1988** [ZiyaoGeng/Recommender-System-with-TF2.0#1]
楼主能补充一下么

**Comment by ZiyaoGeng** [comment]
之前链接没改过来，现在已经修正



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "muyeliuyun"<notifications@github.com&gt;; 
发送时间: 2020年8月25日(星期二) 下午2:07
收件人: "ZiyaoGeng/Recommender-System-with-TF2.0"<Recommender-System-with-TF2.0@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [ZiyaoGeng/Recommender-System-with-TF2.0] ml-1m数据集的具体介绍与处理的传送门消失了 (#1)





 
楼主能补充一下么
