### ISSUE TITLE
请问FFM为什么在md文件里说无法实际使用呢？

### ISSUE THREAD

**Issue by DachuanZhao** [ZiyaoGeng/Recommender-System-with-TF2.0#11]

**Comment by ZiyaoGeng** [comment]
因为，我只是简单的按照论文的意图复现了下，跑起来很慢（用了太多for循环），所以无法实际价值。在CTR等比赛中，一般会使用github（https://github.com/ycjuan/libffm）的C++包进行调用

**Comment by DachuanZhao** [comment]
get，感谢回复。我准备照你实现的改改~~~

**Comment by DachuanZhao** [comment]
> 因为，我只是简单的按照论文的意图复现了下，跑起来很慢（用了太多for循环），所以无法实际使用。在CTR等比赛中，一般会使用github（https://github.com/ycjuan/libffm ）的C++包进行调用

最后还是用了libffm和xlearn的实现，tf确实有点慢。。。 请问一下你部署过ffm嘛？，想知道这样的ffm模型怎么部署和进行实时online-learning  囧rz
