### ISSUE TITLE
din模型训练有问题

### ISSUE THREAD

**Issue by wanglc2008** [ZiyaoGeng/Recommender-System-with-TF2.0#13]
你好，din模型和你csdn上写的不一样，csdn上输入有用户id，github上没有了，为啥？而且github上的运行会报错

**Comment by ZiyaoGeng** [comment]
因为我将DIN重写过了，之前的是仿照DIN的开源代码写的。之前的现在放在DIN/old文件下。当前代码是可以运行的，你可以再检查下
