### ISSUE TITLE
请问为什么用同样的数据集运行时会报错ValueError

### ISSUE THREAD

**Issue by gyy1225** [ZiyaoGeng/Recommender-System-with-TF2.0#3]
代码和数据集是一样的，但是运行的时候会报错：
/keras/layers/embeddings.py:128 compute_output_shape *
        raise ValueError(

    ValueError: "input_length" is 1, but received input has shape (None,)

**Comment by ZiyaoGeng** [comment]
能说明下是哪个模型么

**Comment by ZiyaoGeng** [comment]
> 代码和数据集是一样的，但是运行的时候会报错：
> /keras/layers/embeddings.py:128 compute_output_shape *
> raise ValueError(
> 
> ```
> ValueError: "input_length" is 1, but received input has shape (None,)
> ```

能说明下是哪个模型么？

**Comment by gyy1225** [comment]
> > 代码和数据集是一样的，但是运行的时候会报错：
> > /keras/layers/embeddings.py:128 compute_output_shape *
> > raise ValueError(
> > ```
> > ValueError: "input_length" is 1, but received input has shape (None,)
> > ```
> 
> 能说明下是哪个模型么？

哦哦忘了说了，是Wide&Deep模型，用的kaggle criteo数据集。谢谢

**Comment by ZiyaoGeng** [comment]
> > > 代码和数据集是一样的，但是运行的时候会报错：
> > > /keras/layers/embeddings.py:128 compute_output_shape *
> > > raise ValueError(
> > > ```
> > > ValueError: "input_length" is 1, but received input has shape (None,)
> > > ```
> > 
> > 
> > 能说明下是哪个模型么？
> 
> 哦哦忘了说了，是Wide&Deep模型，用的kaggle criteo数据集。谢谢

我线下测试了一下，是正确的，这个报错应该是输入的问题吧

**Comment by gyy1225** [comment]
> > > > 代码和数据集是一样的，但是运行的时候会报错：
> > > > /keras/layers/embeddings.py:128 compute_output_shape *
> > > > raise ValueError(
> > > > ```
> > > > ValueError: "input_length" is 1, but received input has shape (None,)
> > > > ```
> > > 
> > > 
> > > 能说明下是哪个模型么？
> > 
> > 
> > 哦哦忘了说了，是Wide&Deep模型，用的kaggle criteo数据集。谢谢
> 
> 我线下测试了一下，是正确的，这个报错应该是输入的问题吧

嗯嗯，我再仔细看看是不是我哪里写错了，谢谢你。
