### ISSUE TITLE
deepfm模型mlp层输出shape的bug

### ISSUE THREAD

**Issue by linkaixin22** [ZiyaoGeng/Recommender-System-with-TF2.0#75]
deepfm模型中mlp部分的输出deep_outputs经过dense层后的shape是（batch_size, 1, 1)而不是（batch_size, 1），
wide_outputs的shape是(batch_size, 1)，这边会报错，需要增加一个reshape：
deep_outputs = tf.reshape(deep_outputs, shape=(-1, 1))

**Comment by ZiyaoGeng** [comment]
Tensorflow2.7及以上可以，TF2.5~2.6的兼容性之后调整

**Comment by linkaixin22** [comment]
好的，谢谢楼主

**Comment by linkaixin22** [comment]
好的，谢谢楼主
