### ISSUE TITLE
SASRec训练出错

### ISSUE THREAD

**Issue by boluochuile** [ZiyaoGeng/Recommender-System-with-TF2.0#8]
没改动代码，训练完一个epoch就报错啊
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1224 test_function  *
        return step_function(self, iterator)
    /content/dataset/SASRec/model.py:63 call  *
        dense_inputs, sparse_inputs, seq_inputs, item_inputs = inputs

    ValueError: not enough values to unpack (expected 4, got 2)

**Comment by ZiyaoGeng** [comment]
已更新，是因为验证集写的方式不对，差了TF2.3的API，
validation_data = tuple (x_val, y_val) of Numpy arrays or tensors，
为一个元组，将[val_X, val_y]改为(val_X, val_y)即可

**Comment by boluochuile** [comment]
是的，谢谢~
